version: '2'

services:
  local:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
