version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
    ports:
      - "0.0.0.0:5432:5432"
    container_name: postgres
  redis:
    image: redis
    container_name: redis
    ports:
      - "0.0.0.0:6379:6379"
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    command: bash -x ./compose/django/gunicorn.sh
    env_file: .env
    ports:
      - "0.0.0.0:5000:5000"
    container_name: django
