# Generated by Django 2.0.1 on 2018-10-20 02:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import ssrd.home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(verbose_name='简介')),
                ('culture', models.TextField(verbose_name='企业文化')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('postcode', models.CharField(max_length=10, verbose_name='邮编')),
                ('tel', models.CharField(default='', max_length=20, verbose_name='电话')),
                ('fax', models.CharField(default='', max_length=20, verbose_name='传真')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品类别')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='CharityActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章主题')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='文档名称')),
                ('source', models.SmallIntegerField(choices=[(9, '荣誉资质'), (1, '合作伙伴'), (2, '操作视频'), (3, '文档下载'), (4, '合同'), (5, '签证'), (6, '常用软件'), (7, '设计方案'), (8, '说明文档'), (0, '全部文档')], verbose_name='来源')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='背景图片')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('created', models.DateField(default='2017-09-15', verbose_name='项目时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('created', models.DateField(default='2017-09-15', verbose_name='项目时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('picture', models.ImageField(upload_to='', verbose_name='背景图片')),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(db_index=True, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='回答')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='背景图片')),
                ('link', models.TextField(verbose_name='行业链接')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('job', models.TextField(max_length=100, verbose_name='职位')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='手机号码')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.SmallIntegerField(choices=[(0, '全部新闻'), (4, '首页公告'), (1, '公司新闻'), (2, '公益咨询'), (3, '咨询文章')], default=1, verbose_name='类型')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品编号')),
                ('description', models.TextField(verbose_name='产品描述')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='产品内容')),
                ('background', models.ImageField(upload_to='', verbose_name='背景图片')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=models.SET(ssrd.home.models.defaultCategory), to='home.Category', verbose_name='产品分类')),
                ('pictures', models.ManyToManyField(to='home.Images', verbose_name='产品插图')),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='职位名称')),
                ('salary', models.CharField(max_length=50, verbose_name='薪资待遇')),
                ('jobDetail', models.TextField(verbose_name='职位简介')),
                ('jobResponsibilities', models.TextField(verbose_name='岗位职责')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地点')),
                ('number', models.CharField(default='1', max_length=20, verbose_name='招聘数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网点名称')),
                ('linkman', models.CharField(max_length=50, verbose_name='联系人')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系手机')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePromise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('summary', models.TextField(default='', verbose_name='简介摘要')),
                ('picture', models.ImageField(upload_to='', verbose_name='简介摘要插图')),
                ('introduction', models.TextField(default='', verbose_name='系统介绍')),
                ('systemFeature', models.TextField(default='', verbose_name='系统特性')),
                ('structure', models.ImageField(null=True, upload_to='', verbose_name='系统结构')),
                ('funtionalFeature', models.TextField(default='', verbose_name='功能特性')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
                ('pictures', models.ManyToManyField(to='home.Images', verbose_name='系统插图')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('description', models.TextField(verbose_name='描述')),
                ('address', models.CharField(max_length=100, verbose_name='工程地址')),
                ('content', models.TextField(verbose_name='工程内容')),
                ('picture', models.ImageField(upload_to='', verbose_name='背景图片')),
                ('created', models.DateField(default='2017-09-15', verbose_name='项目时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pictures', models.ManyToManyField(to='home.Images', verbose_name='系统案例插图')),
                ('systems', models.ManyToManyField(related_name='systemCases', to='home.System', verbose_name='系统')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('link', models.CharField(max_length=255, verbose_name='链接')),
                ('picture', models.ImageField(upload_to='', verbose_name='背景图片')),
            ],
        ),
    ]
