# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='cooperativePartner',
            field=models.TextField(verbose_name='合作伙伴'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='culture',
            field=models.TextField(verbose_name='企业文化'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='honour',
            field=models.TextField(verbose_name='荣耀'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='introduction',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='questioin',
            field=models.TextField(verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(verbose_name='反馈内容'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mobile',
            field=models.IntegerField(blank=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='产品类别'),
        ),
        migrations.AlterField(
            model_name='recruitmentcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='职位名称'),
        ),
    ]
