# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("home", "0002_auto_20171102_2219")]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=50, verbose_name="产品名称"),
                ),
                ("description", models.TextField(verbose_name="产品描述")),
                ("summary", models.TextField(verbose_name="产品概述")),
                ("techParameter", models.TextField(verbose_name="技术参数")),
                ("domain", models.TextField(verbose_name="应用领域")),
                ("other", models.TextField(verbose_name="其他")),
                ("background", models.ImageField(upload_to="", verbose_name="背景图片")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.ProductCategory",
                        verbose_name="产品分类",
                    ),
                ),
                (
                    "pictures",
                    models.ManyToManyField(to="home.Images", verbose_name="产品插图"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("summary", models.TextField(verbose_name="简介摘要")),
                ("picture", models.ImageField(upload_to="", verbose_name="简介摘要插图")),
                ("introduction", models.TextField(verbose_name="系统介绍")),
                ("systemFeature", models.TextField(verbose_name="系统特性")),
                (
                    "structure",
                    models.ImageField(null=True, upload_to="", verbose_name="系统结构"),
                ),
                ("funtionalFeature", models.TextField(verbose_name="功能特性")),
                ("rank", models.IntegerField(default=100, verbose_name="排序")),
                (
                    "pictures",
                    models.ManyToManyField(to="home.Images", verbose_name="系统插图"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemCase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("summary", models.TextField(verbose_name="摘要")),
                ("description", models.TextField(verbose_name="描述")),
                ("address", models.CharField(max_length=100, verbose_name="工程地址")),
                ("content", models.TextField(verbose_name="工程内容")),
                ("picture", models.ImageField(upload_to="", verbose_name="背景图片")),
                (
                    "created",
                    models.DateField(default="2017-09-15", verbose_name="项目时间"),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "pictures",
                    models.ManyToManyField(to="home.Images", verbose_name="系统案例插图"),
                ),
                (
                    "systems",
                    models.ManyToManyField(
                        related_name="systemCases", to="home.System", verbose_name="系统"
                    ),
                ),
            ],
        ),
    ]
