# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170816_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='背景图片')),
                ('link', models.TextField(verbose_name='行业链接')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('summary', models.TextField(verbose_name='简介摘要')),
                ('introduction', models.TextField(verbose_name='系统介绍')),
                ('feature', models.TextField(verbose_name='功能特性')),
                ('structure', models.ImageField(null=True, upload_to='', verbose_name='系统结构')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
            ],
        ),
        migrations.AlterField(
            model_name='faqs',
            name='rank',
            field=models.IntegerField(default=100, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='servicenet',
            name='rank',
            field=models.IntegerField(default=100, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='servicepromise',
            name='rank',
            field=models.IntegerField(default=100, verbose_name='排序'),
        ),
    ]
