# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171105_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '全部新闻'), (1, '公司新闻'), (2, '公益咨询')], default=1, verbose_name='类型'),
        ),
    ]
