# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170826_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='category',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='地点'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='number',
            field=models.SmallIntegerField(default=1, verbose_name='招聘数量'),
        ),
    ]
