# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170914_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='detail',
            new_name='jobDetail',
        ),
    ]
