# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_news_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='文档名称'),
        ),
    ]
