# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170914_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('job', models.TextField(max_length=100, verbose_name='职位')),
                ('mobile', models.IntegerField(blank=True, verbose_name='手机号码')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('attatchment', models.FileField(upload_to='', verbose_name='附件')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
