# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('source', models.SmallIntegerField(choices=[(0, '荣誉资质'), (1, '合作伙伴')], verbose_name='来源')),
                ('file', models.SmallIntegerField(max_length=100, verbose_name='名称')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='created',
        ),
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
