# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170914_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='', verbose_name='文件'),
        ),
    ]
