# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170914_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='number',
            field=models.CharField(default='1', max_length=20, verbose_name='招聘数量'),
        ),
    ]
