# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170915_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDemonstration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('description', models.TextField(verbose_name='描述')),
                ('address', models.CharField(max_length=100, verbose_name='工程地址')),
                ('content', models.TextField(verbose_name='工程内容')),
                ('picture', models.ImageField(upload_to='', verbose_name='背景图片')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
