# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_systemdemonstration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemDemonstration',
        ),
    ]
