# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_systemdemonstration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDemonstration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('description', models.TextField(verbose_name='描述')),
                ('address', models.CharField(max_length=100, verbose_name='工程地址')),
                ('content', models.TextField(verbose_name='工程内容')),
                ('picture', models.ImageField(upload_to='', verbose_name='背景图片')),
                ('picture1', models.ImageField(upload_to='', verbose_name='背景图片小图1')),
                ('picture2', models.ImageField(upload_to='', verbose_name='背景图片小图2')),
                ('picture3', models.ImageField(upload_to='', verbose_name='背景图片小图3')),
                ('created', models.DateField(default='2017-09-15', verbose_name='项目时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
