# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0012_auto_20171121_1336")]

    operations = [
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("link", models.CharField(max_length=255, verbose_name="链接")),
                ("picture", models.ImageField(upload_to="", verbose_name="背景图片")),
            ],
        )
    ]
