# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='funtionalFeature',
            field=models.TextField(default='', verbose_name='功能特性'),
        ),
        migrations.AlterField(
            model_name='system',
            name='introduction',
            field=models.TextField(default='', verbose_name='系统介绍'),
        ),
        migrations.AlterField(
            model_name='system',
            name='summary',
            field=models.TextField(default='', verbose_name='简介摘要'),
        ),
        migrations.AlterField(
            model_name='system',
            name='systemFeature',
            field=models.TextField(default='', verbose_name='系统特性'),
        ),
    ]
