# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_systemdemonstration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='jobResponsibilities',
            field=models.TextField(default='', verbose_name='岗位职责'),
            preserve_default=False,
        ),
    ]
