# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_recruitment_jobresponsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='job',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='servicenet',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='联系手机'),
        ),
    ]
