# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_project_company"),
        ("home", "0014_auto_20171126_1655"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="attatchment"),
        migrations.AddField(
            model_name="job",
            name="attatchment",
            field=models.ManyToManyField(to="users.Documents", verbose_name="附件"),
        ),
    ]
