# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='systemDemonstration',
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
