# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20171015_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('summary', models.TextField(verbose_name='简介摘要')),
                ('summaryPicture', models.ImageField(upload_to='', verbose_name='简介摘要插图')),
                ('introduction', models.TextField(verbose_name='系统介绍')),
                ('systemFeature', models.TextField(verbose_name='系统特性')),
                ('structure', models.ImageField(null=True, upload_to='', verbose_name='系统结构')),
                ('funtionalFeature', models.TextField(verbose_name='功能特性')),
                ('picture1', models.ImageField(upload_to='', verbose_name='现场图片图1')),
                ('picture2', models.ImageField(upload_to='', verbose_name='现场图片图2')),
                ('picture3', models.ImageField(upload_to='', verbose_name='现场图片图3')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
                ('systemDemonstration', models.ManyToManyField(to='home.SystemDemonstration', verbose_name='系统案例')),
            ],
        ),
    ]
