# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDemonstrationPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='systemdemonstration',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='systemdemonstration',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='systemdemonstration',
            name='picture3',
        ),
        migrations.AddField(
            model_name='systemdemonstrationpicture',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SystemDemonstration'),
        ),
    ]
