# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import ssrd.home.models


class Migration(migrations.Migration):

    dependencies = [("home", "0020_auto_20171209_1718")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=models.SET(ssrd.home.models.defaultCategory),
                to="home.Category",
                verbose_name="产品分类",
            ),
        )
    ]
