# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0021_auto_20171209_1728")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(default="", max_length=50, verbose_name="产品编号"),
        )
    ]
