# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='home.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
