# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0023_auto_20171210_2322")]

    operations = [
        migrations.RenameField(
            model_name="faqs", old_name="questioin", new_name="question"
        )
    ]
