# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdemonstration',
            name='products',
            field=models.ManyToManyField(null=True, to='home.Product', verbose_name='产品'),
        ),
    ]
