# Generated by Django 2.0 on 2017-12-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20171211_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='source',
            field=models.SmallIntegerField(choices=[(9, '荣誉资质'), (1, '合作伙伴'), (2, '操作视频'), (3, '文档下载'), (4, '合同'), (5, '签证'), (6, '常用软件'), (7, '设计方案'), (8, '说明文档'), (0, '全部文档')], verbose_name='来源'),
        ),
    ]
