# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20171020_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQs',
        ),
    ]
