# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.SmallIntegerField(choices=[(0, '荣誉资质'), (1, '合作伙伴'), (2, '操作视频'), (3, '文档下载')], verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='职位名称'),
        ),
    ]
