# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20171022_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='questioin',
            field=models.TextField(db_index=True, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='产品名称'),
        ),
    ]
