# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20171022_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='systemdemonstration',
            name='products',
        ),
        migrations.RemoveField(
            model_name='systemdemonstrationpicture',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='system',
            name='systemDemonstration',
        ),
        migrations.DeleteModel(
            name='SystemDemonstration',
        ),
        migrations.DeleteModel(
            name='SystemDemonstrationPicture',
        ),
    ]
