# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20171025_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemCase',
        ),
    ]
