# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_systemcase_systemcasepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcase',
            name='system',
        ),
        migrations.AddField(
            model_name='systemcase',
            name='systems',
            field=models.ManyToManyField(related_name='systemCases', to='home.System', verbose_name='系统'),
        ),
    ]
