# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20171026_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='summaryPicture',
            new_name='picture',
        ),
    ]
