# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('email', '邮箱'), ('mobile', '手机')], default='email', max_length=10, verbose_name='类型')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'credential',
                'verbose_name_plural': 'credential',
            },
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together=set([('user', 'Type')]),
        ),
    ]
