# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        )
    ]
