# Generated by Django 2.0.1 on 2018-10-20 02:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functools
import ssrd.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, verbose_name='username')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='Mobile Phone')),
                ('role', models.SmallIntegerField(choices=[(0, '管理员'), (1, '经理'), (2, '成员'), (10, '个人用户'), (11, '常规用户'), (12, '行业用户'), (13, '分销商')], default=2, verbose_name='用户权限')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.SmallIntegerField(choices=[('全部', -1), ('启用', 1), ('停用', 0)], default=1, verbose_name='状态')),
                ('group', models.ForeignKey(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', on_delete=django.db.models.deletion.CASCADE, related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', ssrd.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='授权码名称')),
                ('code', models.CharField(default=functools.partial(ssrd.users.models.generate_key, *(), **{'bit': 6}), max_length=40, verbose_name='授权码')),
                ('status', models.SmallIntegerField(choices=[('全部', -1), ('启用', 1), ('停用', 0)], default=1, verbose_name='授权码状态')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizecodes', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorizecode', to=settings.AUTH_USER_MODEL, verbose_name='授权码对应用户')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='内容')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Collected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product', verbose_name='收藏的产品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='审核步骤')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='文件名')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dirs', to='users.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
                ('type', models.SmallIntegerField(choices=[(0, '全部文档'), (1, '说明文档'), (2, '常用软件'), (3, '设计方案'), (4, '签证'), (5, '项目材料'), (6, '审核')], default=1, verbose_name='文件类型')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='邀请码所属用户')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='受邀用户')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '全部文档'), (1, '说明文档'), (2, '常用软件'), (3, '设计方案'), (4, '签证'), (5, '项目材料'), (6, '审核')], default=1, verbose_name='文件类型')),
                ('file', models.FileField(max_length=512, upload_to='', verbose_name='文件')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='', max_length=512, verbose_name='文件名')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='所属用户')),
                ('title', models.TextField(verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.SmallIntegerField(choices=[(0, '全部消息')], default=0, verbose_name='消息类型')),
                ('read', models.SmallIntegerField(choices=[('0', '未读'), ('1', '已读')], default=0, verbose_name='已读')),
                ('rank', models.IntegerField(default=100, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='内容')),
                ('code', models.CharField(default=ssrd.users.models.generate_key, max_length=40, verbose_name='订单号')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(default=ssrd.users.models.avator, upload_to='', verbose_name='系统结构')),
                ('name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(auto_now=True, verbose_name='生日')),
                ('company', models.CharField(max_length=255, null=True, verbose_name='所属公司')),
                ('position', models.CharField(max_length=255, null=True, verbose_name='职位')),
                ('qq', models.CharField(max_length=20, null=True, verbose_name='QQ号码')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='地址')),
                ('code', models.CharField(default=ssrd.users.models.generate_key, max_length=40, verbose_name='邀请码')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('type', models.CharField(choices=[('create', '新建项目'), ('maintain', '故障维护'), ('remove', '迁移、拆除'), ('exhibition', '展会协助')], default='create', max_length=20, verbose_name='项目类型')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='内容')),
                ('mobile', models.CharField(blank=True, default='', max_length=11, verbose_name='Mobile Phone')),
                ('status', models.SmallIntegerField(choices=[(1, '下单'), (2, '转发'), (3, '设计方案'), (4, '审核'), (5, '发货'), (6, '实施'), (7, '签字'), (0, '终止')], default=1, verbose_name='项目状态')),
                ('remark', models.TextField(verbose_name='补充说明')),
                ('duration', models.SmallIntegerField(default=1, verbose_name='工期')),
                ('budget', models.SmallIntegerField(default=1, verbose_name='工期')),
                ('linkman', models.CharField(max_length=50, verbose_name='联系人')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='地址')),
                ('company', models.CharField(max_length=255, null=True, verbose_name='所属公司')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attatchment', models.ManyToManyField(to='users.Documents', verbose_name='附件')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目组')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectGroups', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(1, '签字'), (2, '审核'), (3, '协助申请'), (4, '工作日志'), (5, '设计方案'), (6, '发货'), (7, '驳回'), (8, '转发')], default=0, verbose_name='行为')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attatchment', models.ManyToManyField(to='users.Documents', verbose_name='附件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.Project', verbose_name='所属项目')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.ProjectGroup', verbose_name='所属项目组'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='directory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectgroup',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('directory', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('parent', 'name')},
        ),
    ]
