# Generated by Django 2.0.1 on 2018-10-31 07:55

import aspect.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ProjectPermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permission", models.SmallIntegerField(choices=[(1, "只读")], default=1, verbose_name="权限")),
            ],
        ),
        migrations.AlterField(
            model_name="documents",
            name="file",
            field=models.FileField(storage=aspect.storage.FileBrowserStorage(), upload_to="", verbose_name="文件"),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("create", "新建项目"),
                    ("maintain", "故障维护"),
                    ("migrate", "变更、迁移"),
                    ("remove", "拆除类"),
                    ("exhibition", "展会协助"),
                ],
                default="create",
                max_length=20,
                verbose_name="项目类型",
            ),
        ),
        migrations.AddField(
            model_name="projectpermission",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.Project", verbose_name="所属项目"
            ),
        ),
        migrations.AddField(
            model_name="projectpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="所属用户"
            ),
        ),
    ]
