# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170726_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='背景图片'),
        ),
    ]
