# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizecode',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '终止'), (0, '停用'), (1, '启用')], default=1, verbose_name='授权码状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '用户下订单'), (2, '商务部对接转发'), (3, '设计部上传方案报价'), (4, '领导审核'), (5, '客户审核上传确认'), (6, '商务部审核'), (7, '仓库发货'), (8, '工程部实施'), (9, '客户签字确认'), (0, '终止')], default=1, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'ADMIN'), (1, 'BOSS'), (10, '市场部'), (11, '市场部组长'), (12, '市场部组员'), (20, '工程部'), (21, '工程部经理'), (22, '工程部组长'), (23, '工程部组员'), (31, '行业用户'), (32, '分销商'), (41, '个人用户'), (42, '常规用户')], default=1, verbose_name='用户权限'),
        ),
    ]
