# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20171106_1746")]

    operations = [
        migrations.RemoveField(model_name="project", name="user"),
        migrations.RemoveField(model_name="projectlog", name="attatchment"),
        migrations.RemoveField(model_name="projectlog", name="project"),
        migrations.DeleteModel(name="Project"),
        migrations.DeleteModel(name="ProjectLog"),
    ]
