# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170914_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizecode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='authorizecode',
            name='created',
        ),
        migrations.RemoveField(
            model_name='authorizecode',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='authorizecode',
            name='status',
        ),
        migrations.RemoveField(
            model_name='authorizecode',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='authorizecode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
    ]
