# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170927_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizeCode',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
