# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("users", "0007_auto_20171116_2300")]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="项目名称"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("新建项目", "新建项目"),
                            ("故障维护", "故障维护"),
                            ("迁移、拆除", "迁移、拆除"),
                        ],
                        default=0,
                        max_length=20,
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=11,
                        verbose_name="Mobile Phone",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "用户下订单"),
                            (2, "商务部对接转发"),
                            (3, "设计部上传方案报价"),
                            (4, "领导审核"),
                            (5, "客户审核上传确认"),
                            (6, "商务部审核"),
                            (7, "仓库发货"),
                            (8, "工程部实施"),
                            (9, "客户签字确认"),
                            (0, "终止"),
                        ],
                        default=1,
                        verbose_name="项目状态",
                    ),
                ),
                ("remark", models.TextField(verbose_name="补充说明")),
                ("duration", models.SmallIntegerField(default=1, verbose_name="工期")),
                ("budget", models.SmallIntegerField(default=1, verbose_name="工期")),
                (
                    "linkman",
                    models.CharField(max_length=50, unique=True, verbose_name="联系人"),
                ),
                ("content", jsonfield.fields.JSONField(verbose_name="内容")),
                (
                    "address",
                    models.CharField(max_length=255, null=True, verbose_name="地址"),
                ),
                (
                    "picture",
                    models.ImageField(null=True, upload_to="", verbose_name="背景图片"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "attatchment",
                    models.ManyToManyField(to="users.Documents", verbose_name="附件"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.SmallIntegerField(
                        choices=[
                            (0, "签字"),
                            (1, "审核"),
                            (2, "协助申请"),
                            (3, "工作日志"),
                            (4, "设计报价"),
                            (5, "发货"),
                        ],
                        default=0,
                        verbose_name="行为",
                    ),
                ),
                ("content", jsonfield.fields.JSONField(verbose_name="内容")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "attatchment",
                    models.ManyToManyField(to="users.Documents", verbose_name="附件"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="users.Project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
        ),
    ]
