# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_project_projectlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='picture',
        ),
    ]
