# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_authorizecode_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Mobile Phone'),
        ),
    ]
