# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0009_remove_project_picture")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="group",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="users.Group"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="部门"),
        ),
    ]
