# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171008_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizecode',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizecodes', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
