# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171015_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='project',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
