# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20171022_1823'),
        ('users', '0013_auto_20171023_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Product', verbose_name='收藏的产品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
