# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '全部消息')], default=0, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='authorizecode',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '全部'), (0, '停用'), (1, '启用')], default=1, verbose_name='授权码状态'),
        ),
    ]
