# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20171026_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizecode',
            name='name',
            field=models.CharField(default='asd', max_length=50, verbose_name='授权码名称'),
            preserve_default=False,
        ),
    ]
