# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_authorizecode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to=settings.AUTH_USER_MODEL, verbose_name='邀请码所属用户'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='受邀用户'),
        ),
    ]
