# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import ssrd.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20171027_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=ssrd.users.models.generate_key, max_length=40, verbose_name='邀请码'),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
