# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
                ('created', models.DateField(auto_now_add=True, verbose_name='项目时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, '签字'), (1, '审核'), (2, '协助申请'), (3, '工作日志'), (4, '设计报价'), (5, '发货')], default=0, verbose_name='行为')),
                ('content', models.TextField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attatchment', models.ManyToManyField(to='users.Document', verbose_name='附件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.Project', verbose_name='所属项目')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectdynamics',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectDynamics',
        ),
    ]
