# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20171128_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
    ]
