# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20171031_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='文件名'),
        ),
    ]
