# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0022_auto_20171128_2110")]

    operations = [
        migrations.AlterUniqueTogether(
            name="project", unique_together=set([("user", "name")])
        )
    ]
