# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20171205_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='structure',
            new_name='avator',
        ),
    ]
