# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20171205_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avator',
            field=models.ImageField(default='/Users/huangjun/Documents/ssrd/ssrd/static/images/avator_bO5ZAWA.png', upload_to='', verbose_name='系统结构'),
        ),
    ]
