# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20171205_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avator',
            field=models.ImageField(null=True, upload_to='', verbose_name='系统结构'),
        ),
    ]
