# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20171205_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avator',
            field=models.ImageField(default=(b''))
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '下单'), (2, '转发'), (3, '设计报价'), (4, '审核'), (5, '审核'), (6, '审核'), (7, '发货'), (8, '实施'), (9, '签字'), (0, '终止')], default=1, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, '管理员'), (1, '经理'), (2, '成员')], default=2, verbose_name='用户权限'),
        ),
    ]
