# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import ssrd.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20171206_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avator',
            field=models.ImageField(default=ssrd.users.models.avator, upload_to='', verbose_name='系统结构'),
        ),
    ]
