# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ssrd.users.models


class Migration(migrations.Migration):

    dependencies = [("users", "0036_auto_20171206_2227")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="users.Group",
            ),
        )
    ]
