# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ssrd.users.models


class Migration(migrations.Migration):

    dependencies = [("users", "0038_documents_type")]

    operations = [
        migrations.CreateModel(
            name="ProjectGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="部门"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
        ),
        migrations.AlterField(
            model_name="documents",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "全部文档"),
                    (1, "说明文档"),
                    (2, "常用软件"),
                    (3, "设计方案"),
                    (4, "签证"),
                    (5, "项目材料"),
                ],
                default=1,
                verbose_name="文件类型",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("create", "新建项目"),
                    ("maintain", "故障维护"),
                    ("remove", "迁移、拆除"),
                    ("exhibition", "展会协助"),
                ],
                default=0,
                max_length=20,
                verbose_name="项目类型",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="group",
            field=models.ForeignKey(
                default=ssrd.users.models.defaultProjectGroup,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.ProjectGroup",
                verbose_name="所属项目组",
            ),
        ),
    ]
