# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20171215_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='projectGroups', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='name',
            field=models.CharField(max_length=50, verbose_name='部门'),
        ),
        migrations.AlterUniqueTogether(
            name='projectgroup',
            unique_together=set([('name', 'user')]),
        ),
    ]
