# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0042_auto_20171215_1558")]

    operations = [
        migrations.AlterField(
            model_name="projectgroup",
            name="name",
            field=models.CharField(max_length=50, verbose_name="项目组"),
        )
    ]
