# Generated by Django 2.0 on 2017-12-24 16:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ssrd.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20171215_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='审核步骤')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '下单'), (2, '转发'), (3, '设计报价'), (4, '审核'), (7, '发货'), (8, '实施'), (9, '签字'), (0, '终止')], default=1, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='action',
            field=models.SmallIntegerField(choices=[(1, '签字'), (2, '审核'), (3, '协助申请'), (4, '工作日志'), (5, '设计报价'), (6, '发货'), (7, '驳回'), (8, '转发')], default=0, verbose_name='行为'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=ssrd.users.models.defaultUserGroup, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='users.Group'),
        ),
    ]
