# Generated by Django 2.0 on 2017-12-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0044_auto_20171225_0003")]

    operations = [migrations.RenameModel(old_name="Audit", new_name="Config")]
