# Generated by Django 2.0.1 on 2018-01-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20180115_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='文件名')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Directory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '全部文档'), (1, '说明文档'), (2, '常用软件'), (3, '设计方案'), (4, '签证'), (5, '项目材料'), (6, '审核')], default=1, verbose_name='文件类型')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='', max_length=255, verbose_name='文件名')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Directory')),
            ],
        ),
    ]
