# Generated by Django 2.0.1 on 2018-06-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0049_auto_20180620_1455")]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(max_length=512, upload_to="", verbose_name="文件"),
        )
    ]
