# Generated by Django 2.0.1 on 2018-08-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0009_alter_user_last_name_max_length"),
        ("users", "0051_auto_20180828_1823"),
    ]

    operations = [
        migrations.DeleteModel(name="Group"),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Group",
                verbose_name="groups",
            ),
        ),
    ]
