# Generated by Django 2.0.1 on 2018-08-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0053_auto_20180829_1559")]

    operations = [
        migrations.RenameField(model_name="user", old_name="groups", new_name="group")
    ]
